name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull sudhanshugpta/server:latest
            docker pull sudhanshugpta/app:latest
            docker stop backend || true
            docker stop frontend || true
            docker rm backend || true
            docker rm frontend || true
            docker run -d --name backend -p 3000:3000 \
              -e DB_USERNAME="admin" \
              -e DB_PASSWORD="${{secrets.DB_PASSWORD}}" \
              -e DB_NAME="sakila" \
              -e DB_HOST="${{secrets.DB_HOST}}" \
              -e DB_DIALECT="mysql" \
              -e URL="api/v1" \
              -e SERVER_PORT="3000" \
              sudhanshugpta/server:latest
            docker run -d --name frontend -p 5173:5173 \
              -e VITE_API_BASE_URL=http://ec2-13-233-122-156.ap-south-1.compute.amazonaws.com:3000/api/v1 \
              sudhanshugpta/app:latest
